language: php

php:
  - 7.1

dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS laravel_test;"
  - cp .env.travis .env
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate:refresh

script: vendor/bin/phpunit
